### ISSUE TITLE
Specifying homedir for key generation (or Rnp instance as whole)

### ISSUE THREAD

**Issue by skalee** [riboseinc/ruby-rnp#11]
One can load keys from arbitrary location thanks to how `Rnp::Input` is flexible:

https://github.com/riboseinc/ruby-rnp/blob/9293168068d9d9e019aefd5065bf290cbae23c63/examples/password_provider.rb#L22-L25

However, there seems to be no way to generate keys with `Rnp::generate_key` into some custom keyring. As a result, custom homedirs can be created only by spawning a shell and running RNP executable (`rnpkeys --generate-key --homedir=${keydir}`). Is there a plan to change that?

Also a suggestion, perhaps it's better to support `Rnp#homedir` attribute getter and setter instead? Or support appropriate argument in a constructor?

cc @ronaldtse @dewyatt

**Comment by dewyatt** [comment]
> there seems to be no way to generate keys with Rnp::generate_key into some custom keyring.

You can just use `Rnp#save_keys`, unless I'm misunderstanding. If you need them to be separate from the other keys in the rings, use a fresh Rnp instance for generating.

> Also a suggestion, perhaps it's better to support Rnp#homedir attribute getter and setter instead? Or support appropriate argument in a constructor?

A homedir isn't a necessity though, that's one of the key goals with RNP. You can load from memory/disk, save wherever, etc (although G10 is kind of an exception in that it must be loaded/saved to disk).

**Comment by skalee** [comment]
Yes, I think that `Rnp#save_keys` will do the trick. Thank you!
