### ISSUE TITLE
Ability to find key by user's e-mail (or other substring of user id)

### ISSUE THREAD

**Issue by skalee** [riboseinc/ruby-rnp#15]
I got few quick questions.

There's an `Rnp#find_key` method, which searches for public or secret key matching criteria. Key can be searched either by key id, fingerprint, or user id. However, when searching by user id, a complete identifier must be passed.

1. Is there any way to search by user's e-mail?
2. Is e-mail a distinguishable property of key, or is it only a substring of flat user id, at best?
3. Is there a neat way of finding key by substring of its user id, other than iterating through `Rnp#userids`?

Thanks :)

**Comment by ronaldtse** [comment]
This is also related to https://github.com/riboseinc/ruby-rnp/issues/17 . Hopefully we get better Enumerators 👍

**Comment by skalee** [comment]
One more question. Given following possibilities:

```ruby
rnp.each_fingerprint do |x|
  k = rnp.find_key(fingerprint: x)
  break k if is_this_key_im_looking_for?(k)
end

rnp.each_userid do |x|
  k = rnp.find_key(userid: x)
  break k if is_this_key_im_looking_for?(k)
end

rnp.each_keyid do |x|
  k = rnp.find_key(keyid: x)
  break k if is_this_key_im_looking_for?(k)
end
```

Are there any important differences in performance I should care about?

**Comment by dewyatt** [comment]
@skalee A bit late, but there shouldn't be *that* much of a difference between them. Userid may involve some extra work internally IIRC, but these blocks here do ~140k/s (140/ms) queries on my machine, unless I'm mistaken..

**Comment by ronaldtse** [comment]
@dewyatt in this case is it better to internalize such code (i.e. simplify what the user needs to know), or document this behavior in the README so that others know how to find key by "x"?
