### ISSUE TITLE
Ability to derive public key from secret key

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/ruby-rnp#26]
Just wondering if it's possible to derive the public part from a GPG secret key?

**Comment by ribose-jeffreylau** [comment]
👌

**Comment by dewyatt** [comment]
Waiting on [rnp 0.11.0](https://github.com/riboseinc/rnp/pull/744). That should resolve this (best to use ruby-rnp 1.0.4 so all tests pass).

**Comment by dewyatt** [comment]
Fixed in librnp a few months ago
