### ISSUE TITLE
Docs: View on GitHub links are broken

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/ruby-rnp#33]
As an example, I got 404 when clicking “View on GitHub” around https://www.rubydoc.info/github/riboseinc/ruby-rnp/Rnp#initialize-instance_method. Not sure if this is an issue with RubyDoc or this project’s configuration but it’d help people make use of Ruby bindings for RNP if they could look up code more easily from docs (especially for now in absence of beginner-friendly tutorials/guides).

**Comment by dewyatt** [comment]
Thanks for pointing this out, it looks like the link assumes a branch called `Rnp` exists for some reason - I'll have to look into it.

**Comment by dewyatt** [comment]
Ok it looks like this is an issue with rubydoc.info that has been around for a few years.
The fix is easy, I just need to add the branch to the end of the URL.
Instead of: https://www.rubydoc.info/github/riboseinc/ruby-rnp/
We can use: https://www.rubydoc.info/github/riboseinc/ruby-rnp/master/

**Comment by dewyatt** [comment]
Should be fixed in https://github.com/riboseinc/ruby-rnp/commit/a013151345a82bc0bd237cb47de74b6a08621347
