### ISSUE TITLE
Thread-safety question

### ISSUE THREAD

**Issue by skalee** [riboseinc/ruby-rnp#8]
Can I assume that `Rnp` instance is thread-safe? Can I call multiple methods on a single instance simultaneously, or should I guard calls with a mutex?

cc @dewyatt

**Comment by dewyatt** [comment]
Currently there is no internal synchronization so you'll definitely want to synchronize manually.
(Depending on what you're doing, you may be better off using multiple instances of `Rnp`, if possible)

**Comment by skalee** [comment]
Thanks a lot!
